<a href="https://colab.research.google.com/github/soujanya-vattikolla/Machine-Learning-Tutorial/blob/main/SaveModelUsingJoblibAndPickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
# read the csv file
homedf = pd.read_csv("homeprices.csv")
homedf

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
# Create linear regression object
model = linear_model.LinearRegression()
# fit the data
model.fit(homedf[['area']],homedf.price) 


LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Save the model using pickle

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as f: # wb means write binary data
      pickle.dump(model,f)  # dumps the model and saved into a file

Load Saved Model

In [14]:
with open('model_pickle','rb') as f: # rb means read mode
      modl_pckl = pickle.load(f) # the model has been loaded from a file  into the memory and modl_pckl is the object

In [15]:
modl_pckl.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

We can easily share the trained model (model_pickle) to others.

Save Trained Model Using joblib

joblib is most efficient on objects that carry large numpy arrays.

In [17]:
import joblib

In [18]:
joblib.dump(model,'model_joblib')  # saves the model to model_joblib file

['model_joblib']

In [19]:
# load the saved model

modl_joblb = joblib.load('model_joblib') 
modl_joblb

LinearRegression()

In [20]:
# using the modl_joblb object we can predict

modl_joblb.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [21]:
modl_joblb.coef_   # coef is same as before model.coef_

array([135.78767123])

In [22]:
modl_joblb.intercept_   #intercept is also same as before model.intercept_

180616.43835616432