<a href="https://colab.research.google.com/github/soujanya-vattikolla/ML-Basics-Definitions/blob/main/Udemy_PythonforDataAnalysis_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nump Arrays**

In [ ]:
import numpy as np

In [ ]:
# 2d array
my_arr = [[1,2,3],[3,4,5]]

np.array(my_arr)

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
# identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# random integers 

randarr = np.random.randint(0,50,10)
randarr

array([46,  8, 26, 32, 49, 12, 41, 46, 31,  6])

In [ ]:
# maximum value

randarr.max()

49

In [ ]:
# minimum value

randarr.min()

6

In [ ]:
# to get the location of max value

randarr.argmax()

9

In [ ]:
# to get the location of min value

randarr.argmin()

9

In [ ]:
# Arthimetic
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan

arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

**NumPy Exercises**

1.Create an array of 10 zeros

In [ ]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2.Create an array of 10 ones

In [ ]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3.Create an array of 10 fives

In [ ]:
arr_fives = np.ones(10)*5
arr_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

4.Create an array of the integers from 10 to 50

In [ ]:
arr_int = np.arange(10,51)
arr_int


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5.Create an array of all the even integers from 10 to 50

In [ ]:
arr_even = np.arange(10,51,2)
arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

6.Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr_matrix = np.arange(9).reshape(3,3)
arr_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7.Create a 3x3 identity matrix

In [ ]:
arr_identity = np.eye(3)
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8.Use NumPy to generate a random number between 0 and 1

In [ ]:
arr_rand = np.random.randn(1)
arr_rand

array([-1.0853318])

9.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr_randnum = np.random.rand(5,5)
arr_randnum

array([[0.34824889, 0.95295589, 0.90944755, 0.88053727, 0.66980816],
       [0.76833952, 0.37789096, 0.64776381, 0.92399032, 0.67771167],
       [0.6854647 , 0.78589228, 0.52848809, 0.35045155, 0.40244618],
       [0.93341092, 0.046604  , 0.54107853, 0.4854851 , 0.76271093],
       [0.39924448, 0.12324773, 0.57923703, 0.33407078, 0.19890436]])

10.Create the following matrix:



In [ ]:
# array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [ ]:
rand_matrix = np.arange(1,101)
print(rand_matrix)
print()
rand_matrix.reshape(10,10)/100

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]



array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

11.Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
# array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [ ]:
arr_linspace = np.linspace(0,1,20)
arr_linspace

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Numpy Indexing and Selection**


In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

In [ ]:
# output: array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])

In [ ]:
mat[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Get the sum of all the values in mat
np.sum(mat)

325

In [ ]:
# Get the standard deviation of the values in mat
np.std(mat)

7.211102550927978

In [ ]:
# Get the sum of all the columns in mat
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])